SELECT TOP (1000) [id]
      ,[customer_name]
      ,[btp]
      ,[category]
      ,[match_count]
      ,[total_transactions]
      ,[match_percentage]
      ,[last_line_number]
      ,[created_date]
  FROM [POWERAPPS].[dbo].[MASTER_CUSTOMER_BTP_PATTERN]
