SELECT [distributor]
      ,[market_chanel]
      ,[customer_code]
      ,[customer_name]
      ,[kabupaten_kota]
      ,[fss_name]
      ,[fss_code]
      ,[fss_type]
      ,[sales_executive]
      ,[aspm]
  FROM [POWERAPPS].[dbo].[MP_FSS_KC_REFERENCE_09_06_2026]
