SELECT [distributor]
      ,[region]
      ,[fresh_dry]
      ,[market_chanel]
      ,[fss_name]
      ,[fss_code]
      ,[fss_type]
      ,[aspm]
  FROM [POWERAPPS].[dbo].[MP_FSS_DIST_REFERENCE_09_06_2026]
