IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='Distributors' AND xtype='U')

CREATE TABLE [Distributors] (

    [Id] BIGINT IDENTITY(1,1) PRIMARY KEY,

    [Distributor] VARCHAR(255) NOT NULL,

    [SubRegionId] BIGINT NOT NULL

);
 
INSERT INTO [distributors] ([distributor], [sub_region_id]) VALUES

('COOLKAS', '1'),

('CV. ALADIN JAYA', '10'),

('CV. INDO BANGKA PERKASA', '10'),

('CV. JARI PERKASA', '8'),

('CV. MULTI MANDIRI JAYAPURA', '11'),

('CV. OKAJE RUTENG', '8'),

('CV. ROYAL GALAXY', '8'),

('CV. SAMPURNA', '8'),

('CV. SUMBER BARU DAMAI SEJAHTERA - AMBON', '11'),

('CV. TELAGA MAS', '10'),

('DIRECT', '4'),

('DIRECT', '6'),

('DIRECT', '8'),

('DIRECT', '3'),

('DIRECT', '1'),

('DIRECT', '2'),

('DIRECT', '10'),

('DISTRIBUTOR', '4'),

('DISTRIBUTOR', '6'),

('DISTRIBUTOR', '8'),

('DISTRIBUTOR', '5'),

('DISTRIBUTOR', '11'),

('DISTRIBUTOR', '9'),

('DISTRIBUTOR', '3'),

('DISTRIBUTOR', '1'),

('DISTRIBUTOR', '2'),

('DISTRIBUTOR', '7'),

('DISTRIBUTOR', '10'),

('INDIRECT', '4'),

('INDIRECT', '6'),

('INDIRECT', '2'),

('KACS', '1'),

('NATIONAL', '1'),

('PT Puji Surya Indah Pasuruan', '6'),

('PT. ANUGRAH BERKAT ANDA - ACEH', '7'),

('PT. ANUGRAH BERKAT ANDA - MEDAN', '7'),

('PT. BARU INDAH', '5'),

('PT. BERKAT LARIS GEMILANG - LUWUK', '9'),

('PT. BERKAT LARIS GEMILANG', '9'),

('PT. BESTINDO PERSADA BINTAN', '10'),

('PT. BINTAN INDAH SEJATI', '10'),

('PT. CAHAYA AGUNG CEMERLANG - SEMARANG', '4'),

('PT. CAHAYA AGUNG CEMERLANG - TEGAL', '4'),

('PT. CAHAYA INTI PUTRA SEJAHTERA - BANDUNG', '2'),

('PT. CAHAYA INTI PUTRA SEJAHTERA - CIREBON', '2'),

('PT. CAHAYA INTI PUTRA SEJAHTERA - TASIK', '2'),

('PT. CAHAYA LESTARI TEGUH MAKMUR', '10'),

('PT. CATUR SENTOSA ANUGERAH - BANDUNG', '2'),

('PT. CATUR SENTOSA ANUGERAH - BAYUR', '3'),

('PT. CATUR SENTOSA ANUGERAH - BEKASI', '3'),

('PT. CATUR SENTOSA ANUGERAH - BELITUNG', '10'),

('PT. CATUR SENTOSA ANUGERAH - BOGOR', '3'),

('PT. CATUR SENTOSA ANUGERAH - CENGKARENG', '3'),

('PT. CATUR SENTOSA ANUGERAH - CIJANTUNG', '3'),

('PT. CATUR SENTOSA ANUGERAH - CIKUPA', '3'),

('PT. CATUR SENTOSA ANUGERAH - CIREBON', '2'),

('PT. CATUR SENTOSA ANUGERAH - JAKARTA UTARA', '3'),

('PT. CATUR SENTOSA ANUGERAH - JAMBI', '10'),

('PT. CATUR SENTOSA ANUGERAH - KUDUS', '4'),

('PT. CATUR SENTOSA ANUGERAH - LAMPUNG', '10'),

('PT. CATUR SENTOSA ANUGERAH - PALEMBANG', '10'),

('PT. CATUR SENTOSA ANUGERAH - PEKANBARU', '10'),

('PT. CATUR SENTOSA ANUGERAH - PURWOKERTO', '4'),

('PT. CATUR SENTOSA ANUGERAH - RAJEG', '3'),

('PT. CATUR SENTOSA ANUGERAH - SEMARANG', '4'),

('PT. CATUR SENTOSA ANUGERAH - SERANG', '3'),

('PT. CATUR SENTOSA ANUGERAH - SOLO', '4'),

('PT. CATUR SENTOSA ANUGERAH - SUBANG', '2'),

('PT. CATUR SENTOSA ANUGERAH - SUKABUMI', '2'),

('PT. CATUR SENTOSA ANUGERAH - TANGERANG SELATAN', '3'),

('PT. CATUR SENTOSA ANUGERAH - TASIKMALAYA', '2'),

('PT. CATUR SENTOSA ANUGERAH - TEGAL', '4'),

('PT. CATUR SENTOSA ANUGERAH - YOGYAKARTA', '4'),

('PT. CIPTA ANUGERAH REZEKI', '4'),

('PT. CLASSIC FINE FOODS', '1'),

('PT. COLAMAS INDAH SEJATI', '10'),

('PT. COLAMASS SUKSES MANDIRI', '10'),

('PT. DINETA JAYA', '8'),

('PT. EINGANG HARAPAN INDAH', '5'),

('PT. EKAPUTRA PRADA INDONESIA', '10'),

('PT. HARUM PAPUA PERKASA', '11'),

('PT. INDODAIRY CONTINENTAL - KABANJAHE', '7'),

('PT. INDODAIRY CONTINENTAL - KISARAN', '7'),

('PT. INDODAIRY CONTINENTAL - MEDAN', '7'),

('PT. INDODAIRY CONTINENTAL - PADANG SIDEMPUAN', '7'),

('PT. INDODAIRY CONTINENTAL - SIANTAR', '7'),

('PT. INTAN SUKSES INSPIRASI', '7'),

('PT. JERINDO JAYA ABADI - MALANG', '6'),

('PT. JERINDO JAYA ABADI - SURABAYA', '6'),

('PT. KELOLA PANGAN INDONESIA', '7'),

('PT. KURNIA MAJU PERKASA', '7'),

('PT. MARTINDO FINE FOODS', '10'),

('PT. MENARA NUSANTARA PERSADA - PALEMBANG', '10'),

('PT. MENARA NUSANTARA PERSADA', '10'),

('PT. MITRA MAS NIAGA', '10'),

('PT. MULTI SUKSES MAKMUR PERKASA', '11'),

('PT. PANDA INDO TUNGGAL', '7'),

('PT. PUJI SURYA INDAH - BABAT', '6'),

('PT. PUJI SURYA INDAH - BANYUWANGI', '6'),

('PT. PUJI SURYA INDAH - JEMBER', '4'),

('PT. PUJI SURYA INDAH - JOMBANG', '6'),

('PT. PUJI SURYA INDAH - KEDIRI', '6'),

('PT. PUJI SURYA INDAH - MADIUN', '6'),

('PT. PUJI SURYA INDAH - MADURA', '6'),

('PT. PUJI SURYA INDAH - MALANG', '6'),

('PT. PUJI SURYA INDAH - PASURUAN', '6'),

('PT. PUJI SURYA INDAH - PROBILINGGO', '6'),

('PT. PUJI SURYA INDAH - PROBOLINGGO', '6'),

('PT. PUJI SURYA INDAH - SURABAYA', '6'),

('PT. PULAU BARU JAYA - BANJARMASIN', '5'),

('PT. PULAU BARU JAYA - PALANGKARAYA', '5'),

('PT. PULAU BARU MANDIRI - SAMARINDA', '5'),

('PT. PULAU BARU SENTOSA', '5'),

('PT. SARI MAKMUR SANJAYA', '4'),

('PT. SINAR ANUGERAH REJEKI BERSAMA - GORONTALO', '9'),

('PT. SINAR ANUGERAH REJEKI BERSAMA - KENDARI', '9'),

('PT. SINAR ANUGERAH REJEKI BERSAMA - MAKASSAR', '9'),

('PT. SINAR ANUGERAH REJEKI BERSAMA - MANADO', '9'),

('PT. SINAR ANUGERAH REJEKI BERSAMA - PARE-PARE', '9'),

('PT. SINAR MAYURI', '8'),

('PT. Sufo Tritama Mandiri', '10'),

('PT. SURYA ANUGRAH SENTOSA', '3'),

('PT. TIGA MUTIARA PRIMA', '4'),

('PT. TIGARAKSA SATRIA - JAKARTA', '3'),

('PT. TIGARAKSA SATRIA - SURABAYA', '6'),

('PT. TIGARAKSA SATRIA - YOGYA', '4'),

('PT. TIRTA PRIMA RASA - BANYUWANGI', '6'),

('PT. TIRTA PRIMA RASA - JEMBER', '6'),

('PT. TIRTA PRIMA RASA - KARANGDUREN', '6'),

('PT. TIRTA PRIMA RASA - KEDIRI', '6'),

('PT. TIRTA PRIMA RASA - MALANG', '6'),

('PT. TIRTA PRIMA RASA - SURABAYA', '6'),

('PT. TRI SAMUDRA', '11'),

('PT. UNI GEMILANG SENTOSA', '3'),

('PT. WAHANA BOGA NUSANTARA - BALI', '8'),

('TRANSPORTER', '1'),

('TRANSPORTER', '12');

('OTHER', '1');
 