-- =====================================================
-- insert_DistributorNew.sql
-- =====================================================
-- Purpose:
--   Insert distributor baru dari DistributorNew.csv ke [dbo].[Distributors]
--   - Hanya INSERT baris yang belum ada (match kolom [Distributor])
--   - Tidak update data existing
--   - Duplikat di CSV (setelah trim) diabaikan
--
-- Sumber data: distributors/DistributorNew.csv
-- Total rows unik: 183
--
-- Default INSERT: SubRegionId = 1, status = active, code & DistributorScm = NULL
-- =====================================================

USE POWERAPPS;
GO

DECLARE @DefaultSubRegionId BIGINT = 1;
DECLARE @DefaultStatus NVARCHAR(50) = N'active';

DECLARE @Source TABLE (
    [Distributor] NVARCHAR(255) NOT NULL
);

INSERT INTO @Source ([Distributor])
SELECT DISTINCT
    CAST(LTRIM(RTRIM(v.[Distributor])) AS NVARCHAR(255))
FROM (VALUES
    (N'COOLKAS'),
    (N'CV. ALADIN JAYA'),
    (N'CV. INDO BANGKA PERKASA'),
    (N'CV. JARI PERKASA'),
    (N'CV. JAYA MAKMUR SAKTI - PALU'),
    (N'CV. MAKMUR BERSAMA MAJU - CIREBON'),
    (N'CV. MAKMUR BERSAMA MAJU CIREBON'),
    (N'CV. MAKMUR SENTOSA - JAMBI'),
    (N'CV. MENARA NUSANTARA PRIMA - BELITUNG'),
    (N'CV. MULTI MANDIRI JAYAPURA'),
    (N'CV. OKAJE RUTENG'),
    (N'CV. ROYAL GALAXY'),
    (N'CV. SAMPURNA'),
    (N'CV. SUMBER BARU DAMAI SEJAHTERA - AMBON'),
    (N'CV. SUMBER MANDIRI - GARUT'),
    (N'CV. SUMBER MANDIRI - TASIKMALAYA'),
    (N'CV. TELAGA MAS'),
    (N'DIRECT'),
    (N'DISTRIBUTOR'),
    (N'INDIRECT'),
    (N'KACS'),
    (N'MGM BOSCO'),
    (N'NATIONAL'),
    (N'PT. ANUGRAH BERKAT ANDA - ACEH'),
    (N'PT. ANUGRAH BERKAT ANDA - MEDAN'),
    (N'PT. BARU INDAH'),
    (N'PT. BERKAT LARIS GEMILANG'),
    (N'PT. BERKAT LARIS GEMILANG - LUWUK'),
    (N'PT. BESTINDO PERSADA BINTAN'),
    (N'PT. BINTAN INDAH SEJATI'),
    (N'PT. CAHAYA AGUNG CEMERLANG - SEMARANG'),
    (N'PT. CAHAYA AGUNG CEMERLANG - TEGAL'),
    (N'PT. CAHAYA INTI PUTRA SEJAHTERA - BANDUNG'),
    (N'PT. CAHAYA INTI PUTRA SEJAHTERA - CIREBON'),
    (N'PT. CAHAYA INTI PUTRA SEJAHTERA - TASIK'),
    (N'PT. CAHAYA LESTARI TEGUH MAKMUR'),
    (N'PT. CATUR SENTOSA ANUGERAH - BANDUNG'),
    (N'PT. CATUR SENTOSA ANUGERAH - BAYUR'),
    (N'PT. CATUR SENTOSA ANUGERAH - BEKASI'),
    (N'PT. CATUR SENTOSA ANUGERAH - BELITUNG'),
    (N'PT. CATUR SENTOSA ANUGERAH - BOGOR'),
    (N'PT. CATUR SENTOSA ANUGERAH - CENGKARENG'),
    (N'PT. CATUR SENTOSA ANUGERAH - CIJANTUNG'),
    (N'PT. CATUR SENTOSA ANUGERAH - CIKUPA'),
    (N'PT. CATUR SENTOSA ANUGERAH - CIREBON'),
    (N'PT. CATUR SENTOSA ANUGERAH - JAKARTA SELATAN'),
    (N'PT. CATUR SENTOSA ANUGERAH - JAKARTA UTARA'),
    (N'PT. CATUR SENTOSA ANUGERAH - JAMBI'),
    (N'PT. CATUR SENTOSA ANUGERAH - KUDUS'),
    (N'PT. CATUR SENTOSA ANUGERAH - LAMPUNG'),
    (N'PT. CATUR SENTOSA ANUGERAH - PALEMBANG'),
    (N'PT. CATUR SENTOSA ANUGERAH - PEKANBARU'),
    (N'PT. CATUR SENTOSA ANUGERAH - PURWOKERTO'),
    (N'PT. CATUR SENTOSA ANUGERAH - RAJEG'),
    (N'PT. CATUR SENTOSA ANUGERAH - SEMARANG'),
    (N'PT. CATUR SENTOSA ANUGERAH - SERANG'),
    (N'PT. CATUR SENTOSA ANUGERAH - SOLO'),
    (N'PT. CATUR SENTOSA ANUGERAH - SUBANG'),
    (N'PT. CATUR SENTOSA ANUGERAH - SUKABUMI'),
    (N'PT. CATUR SENTOSA ANUGERAH - TANGERANG SELATAN'),
    (N'PT. CATUR SENTOSA ANUGERAH - TASIKMALAYA'),
    (N'PT. CATUR SENTOSA ANUGERAH - TEGAL'),
    (N'PT. CATUR SENTOSA ANUGERAH - YOGYAKARTA'),
    (N'PT. CIPTA ANUGERAH REZEKI'),
    (N'PT. CIPTA LANGGENG MITRA SUKSES - GORONTALO'),
    (N'PT. CLASSIC FINE FOODS'),
    (N'PT. COLAMAS INDAH SEJATI'),
    (N'PT. COLAMASS SUKSES MANDIRI'),
    (N'PT. DINETA JAYA'),
    (N'PT. DUTAMASINDO LABORA JAYA - KARAWANG'),
    (N'PT. DUTAMASINDO LABORA JAYA - PURWAKARTA'),
    (N'PT. EINGANG HARAPAN INDAH'),
    (N'PT. EKAPUTRA PRADA INDONESIA'),
    (N'PT. HARUM PAPUA PERKASA'),
    (N'PT. HOSADA PERMAI - BERAU'),
    (N'PT. HOSADA PERMAI - TARAKAN'),
    (N'PT. INDODAIRY CONTINENTAL - KABANJAHE'),
    (N'PT. INDODAIRY CONTINENTAL - KISARAN'),
    (N'PT. INDODAIRY CONTINENTAL - MEDAN'),
    (N'PT. INDODAIRY CONTINENTAL - PADANG SIDEMPUAN'),
    (N'PT. INDODAIRY CONTINENTAL - SIANTAR'),
    (N'PT. INTAN SUKSES INSPIRASI'),
    (N'PT. JAYA MAKMUR SAKTI - PALU'),
    (N'PT. JERINDO JAYA ABADI - BOJONEGORO'),
    (N'PT. JERINDO JAYA ABADI – BOJONEGORO'),
    (N'PT. JERINDO JAYA ABADI - MALANG'),
    (N'PT. JERINDO JAYA ABADI - SURABAYA'),
    (N'PT. KELOLA PANGAN INDONESIA'),
    (N'PT. KURNIA MAJU PERKASA'),
    (N'PT. MAKMUR MANDIRI UTAMA'),
    (N'PT. MAKMUR MANDIRI UTAMA - BANDUNG'),
    (N'PT. MARTINDO FINE FOODS'),
    (N'PT. MASUYA GRAHA TRIKENCANA'),
    (N'PT. MENARA NUSANTARA PERSADA'),
    (N'PT. MENARA NUSANTARA PERSADA - PALEMBANG'),
    (N'PT. MITRA MAS NIAGA'),
    (N'PT. MULTI SUKSES MAKMUR PERKASA'),
    (N'PT. MUTIARA FARMA - AMBON'),
    (N'PT. PANDA INDO TUNGGAL'),
    (N'PT. PERDANA ADHI LESTARI'),
    (N'PT. PERDANA ADHI LESTARI - KOTABUMI'),
    (N'PT. PERDANA ADHI LESTARI - LAMPUNG'),
    (N'PT. PERDANA ADHI LESTARI - METRO'),
    (N'PT. PERMATA SURYA BAHARI'),
    (N'PT. PERMATA SURYA BAHARI - RENGAT'),
    (N'PT. PRATAMA ABADI SANTOSO - PEKALONGAN'),
    (N'PT. PRATAMA ABADI SANTOSO - TEGAL'),
    (N'PT. PRESTASI MITRA DUMAI'),
    (N'PT. PRESTASI MITRA DUMAI - DURI'),
    (N'PT. PRESTASI MITRA DUMAI - UJUNG TANJUNG'),
    (N'PT. PUJI SURYA INDAH - BABAT'),
    (N'PT. PUJI SURYA INDAH - BANYUWANGI'),
    (N'PT. PUJI SURYA INDAH - JEMBER'),
    (N'PT. PUJI SURYA INDAH - JOMBANG'),
    (N'PT. PUJI SURYA INDAH - KEDIRI'),
    (N'PT. PUJI SURYA INDAH - MADIUN'),
    (N'PT. PUJI SURYA INDAH - MADURA'),
    (N'PT. PUJI SURYA INDAH - MALANG'),
    (N'PT. PUJI SURYA INDAH - PASURUAN'),
    (N'PT. PUJI SURYA INDAH - PROBILINGGO'),
    (N'PT. PUJI SURYA INDAH - PROBOLINGGO'),
    (N'PT. PUJI SURYA INDAH - SURABAYA'),
    (N'PT. PULAU BARU JAYA - BANJARMASIN'),
    (N'PT. PULAU BARU JAYA - PALANGKARAYA'),
    (N'PT. PULAU BARU MANDIRI - SAMARINDA'),
    (N'PT. PULAU BARU SENTOSA'),
    (N'PT. SARI MAKMUR SANJAYA'),
    (N'PT. SINAR ANUGERAH REJEKI BERSAMA - GORONTALO'),
    (N'PT. SINAR ANUGERAH REJEKI BERSAMA - KENDARI'),
    (N'PT. SINAR ANUGERAH REJEKI BERSAMA - MAKASSAR'),
    (N'PT. SINAR ANUGERAH REJEKI BERSAMA - MANADO'),
    (N'PT. SINAR ANUGERAH REJEKI BERSAMA - PARE-PARE'),
    (N'PT. SINAR MAYURI'),
    (N'PT. SKYPUTRA PANCASURYA'),
    (N'PT. SKYPUTRA PANCASURYA - SERANG'),
    (N'PT. SKYPUTRA PANCASURYA - TANGERANG'),
    (N'PT. SUBUR MITRA SUKSES - BANGKALAN'),
    (N'PT. SUBUR MITRA SUKSES - BANYUWANGI'),
    (N'PT. SUBUR MITRA SUKSES - BOJONEGORO'),
    (N'PT. SUBUR MITRA SUKSES - JEMBER'),
    (N'PT. SUBUR MITRA SUKSES - KEDIRI'),
    (N'PT. SUBUR MITRA SUKSES - KEPANJEN'),
    (N'PT. SUBUR MITRA SUKSES - KEPANJEN MALANG'),
    (N'PT. SUBUR MITRA SUKSES - MADIUN'),
    (N'PT. SUBUR MITRA SUKSES - MOJOKERTO'),
    (N'PT. SUBUR MITRA SUKSES - PACITAN'),
    (N'PT. SUBUR MITRA SUKSES - PAMEKASAN'),
    (N'PT. SUBUR MITRA SUKSES - PROBOLINGGO'),
    (N'PT. SUBUR MITRA SUKSES - SIDOARJO'),
    (N'PT. SUBUR MITRA SUKSES - SINGOSARI MALANG'),
    (N'PT. SUBUR MITRA SUKSES - SURABAYA'),
    (N'PT. SUBUR MITRA SUKSES - TUBAN'),
    (N'PT. SUBUR MITRA SUKSES - TULUNGAGUNG'),
    (N'PT. Sufo Tritama Mandiri'),
    (N'PT. SUMBER MANDIRI - GARUT'),
    (N'PT. SUMBER MANDIRI - TASIKMALAYA'),
    (N'PT. SURYA ANUGRAH SENTOSA'),
    (N'PT. TIGA MUTIARA PRIMA'),
    (N'PT. TIGARAKSA SATRIA - JAKARTA'),
    (N'PT. TIGARAKSA SATRIA - SURABAYA'),
    (N'PT. TIGARAKSA SATRIA - YOGYA'),
    (N'PT. TIRTA PRIMA RASA - BANYUWANGI'),
    (N'PT. TIRTA PRIMA RASA - JEMBER'),
    (N'PT. TIRTA PRIMA RASA - KARANGDUREN'),
    (N'PT. TIRTA PRIMA RASA - KEDIRI'),
    (N'PT. TIRTA PRIMA RASA - MALANG'),
    (N'PT. TIRTA PRIMA RASA - SURABAYA'),
    (N'PT. TRI SAMUDRA'),
    (N'PT. TULUS MAJU - SUKABUMI'),
    (N'PT. UNI GEMILANG SENTOSA'),
    (N'PT. UNIRAMA DUTA NIAGA - CINANGKA'),
    (N'PT. UNIRAMA DUTA NIAGA - CIRACAS'),
    (N'PT. UNIRAMA DUTA NIAGA - DAAN MOGOT'),
    (N'PT. UNIRAMA DUTA NIAGA - JATIBENING'),
    (N'PT. UNIRAMA DUTA NIAGA - SUNTER'),
    (N'PT. WAHANA BOGA NUSANTARA - BALI'),
    (N'PT. WIRA EKA PERSADATAMA - BONE'),
    (N'PT. WIRA EKA PERSADATAMA - KENDARI'),
    (N'PT. WIRA EKA PERSADATAMA - MAKASSAR'),
    (N'PT. WIRA EKA PERSADATAMA - MANADO'),
    (N'PT. WIRA EKA PERSADATAMA - PALOPO'),
    (N'PT. WIRA EKA PERSADATAMA - PINRANG'),
    (N'TRANSPORTER')
) AS v([Distributor])
WHERE LTRIM(RTRIM(v.[Distributor])) <> '';

BEGIN TRY
    BEGIN TRANSACTION;

    DECLARE @RowsInserted INT = 0;
    DECLARE @RowsSkipped INT = 0;

    SELECT
        s.[Distributor],
        @DefaultSubRegionId AS SubRegionId,
        @DefaultStatus AS [status]
    FROM @Source s
    WHERE NOT EXISTS (
        SELECT 1
        FROM [dbo].[Distributors] d
        WHERE LTRIM(RTRIM(d.[Distributor])) COLLATE Latin1_General_CI_AI
            = s.[Distributor] COLLATE Latin1_General_CI_AI
    )
    ORDER BY s.[Distributor];

    INSERT INTO [dbo].[Distributors] (
        [Distributor],
        [SubRegionId],
        [code],
        [DistributorScm],
        [status]
    )
    SELECT
        s.[Distributor],
        @DefaultSubRegionId,
        NULL,
        NULL,
        @DefaultStatus
    FROM @Source s
    WHERE NOT EXISTS (
        SELECT 1
        FROM [dbo].[Distributors] d
        WHERE LTRIM(RTRIM(d.[Distributor])) COLLATE Latin1_General_CI_AI
            = s.[Distributor] COLLATE Latin1_General_CI_AI
    );

    SET @RowsInserted = @@ROWCOUNT;

    SELECT @RowsSkipped = COUNT(*)
    FROM @Source s
    WHERE EXISTS (
        SELECT 1
        FROM [dbo].[Distributors] d
        WHERE LTRIM(RTRIM(d.[Distributor])) COLLATE Latin1_General_CI_AI
            = s.[Distributor] COLLATE Latin1_General_CI_AI
    );

    COMMIT TRANSACTION;

    SELECT
        @RowsInserted AS RowsInserted,
        @RowsSkipped AS RowsSkipped,
        (SELECT COUNT(*) FROM @Source) AS TotalSourceRows,
        GETDATE() AS SyncedAt,
        N'Insert DistributorNew berhasil' AS Message;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();

    SELECT
        0 AS RowsInserted,
        0 AS RowsSkipped,
        @ErrorMessage AS ErrorMessage;

    RAISERROR(@ErrorMessage, 16, 1);
END CATCH;
GO
