-- =====================================================
-- upsert_DistributorV1.sql
-- =====================================================
-- Purpose:
--   Sync data dari DistributorV1.csv ke [dbo].[Distributors]
--   - Match berdasarkan kolom [Distributor]
--   - Jika ditemukan: UPDATE [code] dan [DistributorScm]
--   - Jika tidak ditemukan: INSERT row baru
--
-- Sumber data: distributors/DistributorV1.csv
-- Total rows: 149
--
-- Catatan:
--   Untuk data baru (INSERT), SubRegionId default = 1 dan status = 'active'.
--   Sesuaikan @DefaultSubRegionId jika perlu sebelum dijalankan.
-- =====================================================

USE POWERAPPS;
GO

DECLARE @DefaultSubRegionId BIGINT = 1;
DECLARE @DefaultStatus NVARCHAR(50) = 'active';

DECLARE @Source TABLE (
    [Distributor] NVARCHAR(255) NOT NULL PRIMARY KEY,
    [code] NVARCHAR(50) NULL,
    [DistributorScm] NVARCHAR(255) NULL
);

INSERT INTO @Source ([Distributor], [code], [DistributorScm])
VALUES
    (N'PT. WAHANA BOGA NUSANTARA - BALI', N'2000000375', N'WBN - BALI'),
    (N'PT. CAHAYA INTI PUTRA SEJAHTERA - BANDUNG', N'2000073047', N'CIPS -  BDG'),
    (N'PT. JERINDO JAYA ABADI - SURABAYA', N'2000133210', N'JERINDO JAYA ABADI - SBY'),
    (N'PT. ANUGRAH BERKAT ANDA - MEDAN', N'2000117190', N'PT. ANUGRAH BERKAT ANDA -  MEDAN'),
    (N'PT. SINAR ANUGERAH REJEKI BERSAMA - MAKASSAR', N'2000072857', N'SINAR ANUGRAH REJEKI BERSAMA - MKSR'),
    (N'PT. INDODAIRY CONTINENTAL - MEDAN', N'2000001539', N'PT. INDODAIRY CONTINENTAL'),
    (N'PT. SURYA ANUGRAH SENTOSA', N'2000147459', N'SURYA ANUGRAH SENTOSA - BOGOR'),
    (N'CV. JARI PERKASA', N'2000144052', N'JARI PERKASA - BALI'),
    (N'PT. CATUR SENTOSA ANUGERAH - CENGKARENG', N'2000160149', N'PT. CATUR SENTOSA ANUGERAH - CENGKARENG'),
    (N'PT. CAHAYA AGUNG CEMERLANG - SEMARANG', N'2000085648', N'CAC - SMRG'),
    (N'PT. MARTINDO FINE FOODS', N'2000121056', N'MARTINDO BATAM'),
    (N'PT. PULAU BARU JAYA - BANJARMASIN', N'2000111661', N'PULAU BARU - BANJARMASIN'),
    (N'PT. SINAR ANUGERAH REJEKI BERSAMA - MANADO', N'2000083688', N'SINAR ANUGRAH REJEKI BERSAMA - SARB MANADO'),
    (N'PT. MENARA NUSANTARA PERSADA - PALEMBANG', N'2000163790', N'PT MENARA NUSANTARA PERSADA - PALEM'),
    (N'PT. PULAU BARU MANDIRI - SAMARINDA', N'2000160185', N'PT. PULAU BARU MANDIRI - SAMARINDA'),
    (N'PT. EKAPUTRA PRADA INDONESIA', N'2000131291', N'EKAPUTRA PRADA - PKU'),
    (N'PT. EINGANG HARAPAN INDAH', N'2000098449', N'EIH - PONTI'),
    (N'PT. DINETA JAYA', N'2000132261', N'DINETA JAYA LOMBOK'),
    (N'PT. TIGA MUTIARA PRIMA', N'2000085669', N'TMP- SOLO'),
    (N'PT. MASUYA GRAHA TRIKENCANA', N'2000085647', N'PT. MASUYA GRAHA TRIKENCANA'),
    (N'PT. JERINDO JAYA ABADI - MALANG', N'1C00526', N'JERINDO JAYA ABADI - MLG'),
    (N'PT. COLAMASS SUKSES MANDIRI', N'2000160187', N'PT. COLAMAS INDAH SEJATI - BATAM'),
    (N'PT. SINAR MAYURI', N'2000117192', N'PT. SINAR MAYURI - DENPASAR'),
    (N'PT. BARU INDAH', N'2000098357', N'PT. BARU INDAH - BALIKPAPAN'),
    (N'PT. WIRA EKA PERSADATAMA - MAKASSAR', N'2000166451', N'WIRA EKA PERSADATAMA MAKASSAR'),
    (N'PT. CATUR SENTOSA ANUGERAH - BANDUNG', N'2000117200', N'PT. CATUR SENTOSA ANUGERAH - BANDUNG'),
    (N'PT. SARI MAKMUR SANJAYA', N'1009PALAGAN', N'SMS - JOGJA'),
    (N'PT. SINAR ANUGERAH REJEKI BERSAMA - KENDARI', N'2000136100', N'SINAR ANUGRAH REJEKI BERSAMA - KENDARI'),
    (N'PT. CAHAYA INTI PUTRA SEJAHTERA - CIREBON', N'2200001796', N'CIPS -  CIREBON'),
    (N'PT. UNI GEMILANG SENTOSA', N'2000153520', N'PT. UNIGEMILANG SENTOSA - JKT'),
    (N'PT. CAHAYA LESTARI TEGUH MAKMUR', N'2000161985', N'PT CAHAYA LESTARI TEGUH MAKMUR - LAMPUNG'),
    (N'PT. CATUR SENTOSA ANUGERAH - LAMPUNG', N'2000160161', N'PT. CATUR SENTOSA ANUGERAH - PEKANBARU'),
    (N'PT. KURNIA MAJU PERKASA', N'2000161947', N'PT. KURNIA MAJU PERKASA - PADANG & PT. KURNIA MAJU PERKASA - BUKIT TINGGI'),
    (N'PT. INTAN SUKSES INSPIRASI', N'2000138396', N'INTAN SUKSES INSPIRASI - PADANG'),
    (N'PT. PUJI SURYA INDAH - SURABAYA', N'2000117193', N'PT. PUJI SURYA INDAH - SURABAYA'),
    (N'PT. CIPTA ANUGERAH REZEKI', N'2000133207', N'PT. CIPTA ANUGERAH REZEKI - PURWOKERTO'),
    (N'PT. TIRTA PRIMA RASA - SURABAYA', N'2000133205', N'TIRTA PRIMA RASA - SBY'),
    (N'PT. MENARA NUSANTARA PERSADA', N'2000161986', N'PT MENARA NUSANTARA PERSADA - BANGKA'),
    (N'PT. ANUGRAH BERKAT ANDA - ACEH', N'2200001581', N'PT. ANUGRAH BERKAT ANDA - TJM'),
    (N'PT. KELOLA PANGAN INDONESIA', N'2000152534', N'PT. KELOLA PANGAN INDONESIA - ACEH'),
    (N'PT. CLASSIC FINE FOODS', N'2000141877', N'PT CLASSIC FINE FOODS INDONESIA'),
    (N'PT. CAHAYA AGUNG CEMERLANG - TEGAL', N'2910085648', N'CAC - KUDUS'),
    (N'PT. SUFO TRITAMA MANDIRI', N'2000133525', N'SUFO TRITAMA MANDIRI'),
    (N'PT. TIRTA PRIMA RASA - KEDIRI', N'2000142165', N'TIRTA PRIMA RASA - KEDIRI'),
    (N'CV. TELAGA MAS', N'2000140158', N'CV. TELAGA MAS - BENGKULU'),
    (N'PT. INDODAIRY CONTINENTAL - SIANTAR', N'2200002056', N'INDODAIRY - SIANTAR'),
    (N'PT. CAHAYA INTI PUTRA SEJAHTERA - TASIK', N'2910073047', N'CIPS -  BDG'),
    (N'PT. TIRTA PRIMA RASA - JEMBER', N'2000141965', N'TIRTA PRIMA RASA - JEMBER'),
    (N'PT. CATUR SENTOSA ANUGERAH - PEKANBARU', N'2000160162', N'PT. CATUR SENTOSA ANUGERAH - PEKANBARU'),
    (N'PT. PERMATA SURYA BAHARI', N'2000165747', N'PT. PERMATA SURYA BAHARI - PKU'),
    (N'PT. BERKAT LARIS GEMILANG', N'2000157805', N'PT. BERKAT LARIS GEMILANG - PALU'),
    (N'PT. PULAU BARU JAYA - PALANGKARAYA', N'2200002085', N'PULAU BARU - BANJARMASIN'),
    (N'PT. CATUR SENTOSA ANUGERAH - TANGERANG SELATAN', N'2TANGERANG', N'PT. CATUR SENTOSA ANUGERAH - BAYUR'),
    (N'PT. CATUR SENTOSA ANUGERAH - PALEMBANG', N'2000147769', N'PT. CATUR SENTOSA ANUGERAH - PEKANBARU'),
    (N'PT. WIRA EKA PERSADATAMA - MANADO', N'2000166450', N'WIRA EKA PERSADATAMA MANADO'),
    (N'PT. BESTINDO PERSADA BINTAN', N'2000164472', N'BESTINDO PERSADA BINTAN'),
    (N'PT. CATUR SENTOSA ANUGERAH - SEMARANG', N'2000160166', N'PT. CATUR SENTOSA ANUGERAH - SEMARANG'),
    (N'PT. WIRA EKA PERSADATAMA - KENDARI', N'2000166452', N'WIRA EKA PERSADATAMA KENDARI'),
    (N'PT. INDODAIRY CONTINENTAL - KISARAN', N'2200002077', N'INDODAIRY - KISARAN'),
    (N'PT. PUJI SURYA INDAH - MALANG', N'2000160142', N'PT. PUJI SURYA INDAH - MALANG'),
    (N'PT. CATUR SENTOSA ANUGERAH - SUKABUMI', N'2000160154', N'PT. CATUR SENTOSA ANUGERAH - SUKABUMI'),
    (N'PT. TIRTA PRIMA RASA - BANYUWANGI', N'2000159271', N'TIRTA PRIMA RASA - BANYUWANGI'),
    (N'CV. JAYA MAKMUR SAKTI - PALU', N'2000166653', N'PT JAYA MAKMUR SAKTI - PALU'),
    (N'CV. OKAJE RUTENG', N'2000157818', N'CV. OKAJE RUTENG'),
    (N'PT. PUJI SURYA INDAH - KEDIRI', N'2000160143', N'PT. PUJI SURYA INDAH - KEDIRI'),
    (N'CV. MULTI MANDIRI JAYAPURA', N'2000162422', N'CV MULTI MANDIRI - JAYAPURA'),
    (N'PT. CATUR SENTOSA ANUGERAH - CIREBON', N'2000117201', N'PT. CATUR SENTOSA ANUGERAH - CIREBON'),
    (N'PT. WIRA EKA PERSADATAMA - PALOPO', N'2000166446', N'WIRA EKA PERSADATAMA PALOPO'),
    (N'PT. CATUR SENTOSA ANUGERAH - SUBANG', N'2000160156', N'PT. CATUR SENTOSA ANUGERAH - SUBANG'),
    (N'PT. MULTI SUKSES MAKMUR PERKASA', N'2000143532', N'PT. MULTI SUKSES MAKMUR PERKASA - SORONG'),
    (N'CV. MAKMUR SENTOSA - JAMBI', N'2000165628', N'CV. MAKMUR SENTOSA - JAMBI'),
    (N'PT. PUJI SURYA INDAH - MADIUN', N'2000160144', N'PT. PUJI SURYA INDAH - MADIUN'),
    (N'CV. SAMPURNA', N'2000136420', N'CV. SAMPURNA - KUPANG'),
    (N'PT. CATUR SENTOSA ANUGERAH - PURWOKERTO', N'2000160164', N'PT. CATUR SENTOSA ANUGERAH - PURWOKERTO'),
    (N'PT. SUBUR MITRA SUKSES - SURABAYA', N'2000167045', N'SUBUR MITRA SUKSES - SURABAYA'),
    (N'PT. CATUR SENTOSA ANUGERAH - JAKARTA UTARA', N'2000JAKPUS', N'BLENDED DISTRIBUTOR AREA JAKARTA'),
    (N'PT. TIRTA PRIMA RASA - MALANG', N'2000133206', N'TIRTA PRIMA RASA - MLG'),
    (N'PT. CATUR SENTOSA ANUGERAH - BOGOR', N'2000117223', N'PT. CATUR SENTOSA ANUGERAH - BOGOR'),
    (N'PT. CATUR SENTOSA ANUGERAH - JAMBI', N'2000126291', N'PT. CATUR SENTOSA ANUGERAH - PEKANBARU'),
    (N'PT. CATUR SENTOSA ANUGERAH - TASIKMALAYA', N'2000160157', N'PT. CATUR SENTOSA ANUGERAH - TASIKMALAYA'),
    (N'PT. JERINDO JAYA ABADI - BOJONEGORO', N'2000165748', N'Jerindo Jaya Abadi - Bojonegoro'),
    (N'CV. SUMBER BARU DAMAI SEJAHTERA - AMBON', N'2000161872', N'CV SUMBER BARU DAMAI SEJAHTERA - AMBON'),
    (N'PT. PUJI SURYA INDAH - JEMBER', N'2200001552', N'PT. PUJI SURYA INDAH - JEMBER'),
    (N'PT. MUTIARA FARMA - AMBON', N'2000166654', N'PT MUTIARA FARMA - AMBON'),
    (N'CV. MENARA NUSANTARA PRIMA - BELITUNG', N'2000165653', N'CV. MENARA NUSANTARA PRIMA - BELITUNG'),
    (N'PT. INDODAIRY CONTINENTAL - PADANG SIDEMPUAN', N'2200002109', N'INDODAIRY - KISARAN'),
    (N'PT. CATUR SENTOSA ANUGERAH - SERANG', N'2000160151', N'PT. CATUR SENTOSA ANUGERAH - SERANG'),
    (N'PT. PRESTASI MITRA DUMAI', N'2000165746', N'PT. PRESTASI MITRA DUMAI'),
    (N'PT. CATUR SENTOSA ANUGERAH - CIJANTUNG', N'2000000CJT', N'BLENDED DISTRIBUTOR AREA JAKARTA'),
    (N'PT. MAKMUR MANDIRI UTAMA', N'2000167371', N'PT. MAKMUR MANDIRI UTAMA - BANDUNG'),
    (N'PT. PUJI SURYA INDAH - BABAT', N'2200002064', N'PT. PUJI SURYA INDAH - BABAT'),
    (N'PT. HOSADA PERMAI - TARAKAN', N'2000165875', N'PT. HOSADA PERMAI TARAKAN'),
    (N'PT. PERMATA SURYA BAHARI - RENGAT', N'2200002120', N'PT. PERMATA SURYA BAHARI - RENGAT'),
    (N'PT. PRATAMA ABADI SANTOSO - TEGAL', N'2000167123', N'PT. PRATAMA ABADI SANTOSO - TEGAL'),
    (N'PT. SKYPUTRA PANCASURYA', N'2000153519', N'SKYPUTRA PANCASURYA - TANGERANG'),
    (N'PT. UNIRAMA DUTA NIAGA - JATIBENING', N'2000167387', N'PT. UNIRAMA DUTA NIAGA - JATIBENING'),
    (N'PT. HOSADA PERMAI - BERAU', N'2000165876', N'PT. HOSADA PERMAI BERAU'),
    (N'PT. CATUR SENTOSA ANUGERAH - TEGAL', N'2000133208', N'PT. CATUR SENTOSA ANUGERAH - TEGAL'),
    (N'PT. PUJI SURYA INDAH - BANYUWANGI', N'2000159871', N'PT. PUJI SURYA INDAH - BANYUWANGI'),
    (N'PT. CATUR SENTOSA ANUGERAH - BELITUNG', N'2000152442', N'PT. CATUR SENTOSA ANUGERAH - BELITUNG'),
    (N'PT. PUJI SURYA INDAH - JOMBANG', N'2000160141', N'PT. PUJI SURYA INDAH - JOMBANG'),
    (N'PT. UNIRAMA DUTA NIAGA - DAAN MOGOT', N'2000167386', N'PT. UNIRAMA DUTA NIAGA - DAAN MOGOT'),
    (N'PT. CATUR SENTOSA ANUGERAH - BEKASI', N'2000132099', N'BLENDED DISTRIBUTOR AREA JAKARTA'),
    (N'PT. PUJI SURYA INDAH - MADURA', N'2200001797', N'PT. PUJI SURYA INDAH - MADURA'),
    (N'PT. PUJI SURYA INDAH - PROBOLINGGO', N'2200002107', N'PT. PUJI SURYA INDAH - PROBOLINGGO'),
    (N'PT. CATUR SENTOSA ANUGERAH - KUDUS', N'2000160165', N'PT. CATUR SENTOSA ANUGERAH - KUDUS'),
    (N'PT. CATUR SENTOSA ANUGERAH - JAKARTA SELATAN', N'2000JAKSEL', N'BLENDED DISTRIBUTOR AREA JAKARTA'),
    (N'PT. TIGARAKSA SATRIA - JAKARTA', N'2000158429', N'TIGARAKSA SATRIA - JAKART'),
    (N'PT. CATUR SENTOSA ANUGERAH - CIKUPA', N'2000CIKUPA', N'BLENDED DISTRIBUTOR AREA JAKARTA'),
    (N'PT. INDODAIRY CONTINENTAL - KABANJAHE', N'2200002100', N'INDODAIRY - SIANTAR'),
    (N'PT. SUBUR MITRA SUKSES - KEPANJEN MALANG', N'2000167052', N'SUBUR MITRA SUKSES - KEPANJEN'),
    (N'PT. WIRA EKA PERSADATAMA - PINRANG', N'2000166985', N'PT. WIRA EKA PERSADATAMA - PINRANG'),
    (N'PT. CATUR SENTOSA ANUGERAH - RAJEG', N'20000RAJEG', N'BLENDED DISTRIBUTOR AREA JAKARTA'),
    (N'PT. SUBUR MITRA SUKSES - JEMBER', N'2000167050', N'SUBUR MITRA SUKSES - JEMBER'),
    (N'PT. PULAU BARU SENTOSA', N'2000160184', N'PT. PULAU BARU SENTOSA - TARAKAN'),
    (N'PT. SUBUR MITRA SUKSES - MADIUN', N'2000167053', N'SUBUR MITRA SUKSES - MADIUN'),
    (N'PT. SUBUR MITRA SUKSES - KEDIRI', N'2000167051', N'SUBUR MITRA SUKSES - KEDIRI'),
    (N'PT. SUBUR MITRA SUKSES - BANYUWANGI', N'2000167048', N'SUBUR MITRA SUKSES - BANYUWANGI'),
    (N'PT. UNIRAMA DUTA NIAGA - SUNTER', N'2000167388', N'PT. UNIRAMA DUTA NIAGA - SUNTER'),
    (N'PT. SUBUR MITRA SUKSES - SIDOARJO', N'2000167059', N'SUBUR MITRA SUKSES - SIDOARJO'),
    (N'PT. SUBUR MITRA SUKSES - SINGOSARI MALANG', N'2000167054', N'SUBUR MITRA SUKSES - MALANG'),
    (N'PT. CIPTA LANGGENG MITRA SUKSES - GORONTALO', N'2000167065', N'CIPTA LANGGENG MITRA SUKSES - GORONTALO'),
    (N'PT. SUBUR MITRA SUKSES - TULUNGAGUNG', N'2000167061', N'SUBUR MITRA SUKSES - TULUNGAGUNG'),
    (N'PT. TIGARAKSA SATRIA - YOGYA', N'2000158429', N'BLENDED DISTRIBUTOR AREA YOGYAKARTA'),
    (N'PT. DUTAMASINDO LABORA JAYA - KARAWANG', N'2000167376', N'PT. DUTAMASINDO LABORAJAYA - KARAWANG'),
    (N'PT. SUBUR MITRA SUKSES - PROBOLINGGO', N'2000167058', N'SUBUR MITRA SUKSES - PROBOLINGGO'),
    (N'PT. PRESTASI MITRA DUMAI - UJUNG TANJUNG', N'2000166865', N'PT. PRESTASI MITRA DUMAI UJUNG TANJUNG'),
    (N'PT. SUBUR MITRA SUKSES - MOJOKERTO', N'2000167055', N'SUBUR MITRA SUKSES - MOJOKERTO'),
    (N'PT. SUBUR MITRA SUKSES - TUBAN', N'2000167060', N'SUBUR MITRA SUKSES - TUBAN'),
    (N'PT. PERDANA ADHI LESTARI - LAMPUNG', N'2000153974', N'PT. PERDANA ADHI LESTARI  - LAMPUNG'),
    (N'PT. SUBUR MITRA SUKSES - BANGKALAN', N'2000167047', N'SUBUR MITRA SUKSES - BANGKALAN'),
    (N'CV. MAKMUR BERSAMA MAJU CIREBON', N'2000167410', N'CV. MAKMUR BERSAMA MAJU CIREBON'),
    (N'PT. PUJI SURYA INDAH - PASURUAN', N'2000000PSR', N'PT. PUJI SURYA INDAH - PROBOLINGGO'),
    (N'PT. TULUS MAJU - SUKABUMI', N'2000167391', N'PT. TULUS MAJU - SUKABUMI'),
    (N'PT. WIRA EKA PERSADATAMA - BONE', N'2000166984', N'PT. WIRA EKA PERSADATAMA - BONE'),
    (N'PT. TIGARAKSA SATRIA - SURABAYA', N'2000158429', N'TIGARAKSA SATRIA - SURABA'),
    (N'PT. PRATAMA ABADI SANTOSO - PEKALONGAN', N'2000167125', N'PT. PRATAMA ABADI SANTOSO - PEKALONGAN'),
    (N'PT. SUBUR MITRA SUKSES - PACITAN', N'2000167056', N'SUBUR MITRA SUKSES - PACITAN'),
    (N'PT. PRESTASI MITRA DUMAI - DURI', N'2000166866', N'PT. PRESTASI MITRA DUMAI DEPO DURI'),
    (N'PT. SUBUR MITRA SUKSES - PAMEKASAN', N'2000167057', N'SUBUR MITRA SUKSES - PAMEKASAN'),
    (N'PT. SUBUR MITRA SUKSES - BOJONEGORO', N'2000167049', N'SUBUR MITRA SUKSES - BOJONEGORO'),
    (N'PT. UNIRAMA DUTA NIAGA - CINANGKA', N'2000167378', N'PT. UNIRAMA DUTA NIAGA - CINANGKA'),
    (N'PT. SUMBER MANDIRI - TASIKMALAYA', N'2000167390', N'PT. SUMBER MANDIRI - TASIKMALAYA'),
    (N'PT. PERDANA ADHI LESTARI - METRO', N'2200002065', N'PT. PERDANA ADHI LESTARI - METRO'),
    (N'PT. UNIRAMA DUTA NIAGA - CIRACAS', N'2000167385', N'PT. UNIRAMA DUTA NIAGA - CIRACAS'),
    (N'PT. DUTAMASINDO LABORA JAYA - PURWAKARTA', N'2000167377', N'PT. DUTAMASINDO LABORAJAYA - PURWAKARTA'),
    (N'PT. SUMBER MANDIRI - GARUT', N'2000167389', N'CV. SUMBER MANDIRI - GARUT'),
    (N'PT. SKYPUTRA PANCASURYA - SERANG', N'2000167399', N'PT. SKYPUTRA PANCASURYA - SERANG'),
    (N'PT. PERDANA ADHI LESTARI - KOTABUMI', N'2000167372', N'PT. PERDANA ADHI LESTARI - KOTABUMI');

BEGIN TRY
    BEGIN TRANSACTION;

    DECLARE @RowsUpdated INT = 0;
    DECLARE @RowsInserted INT = 0;

    -- Preview: data yang akan di-update
    SELECT
        d.[Id],
        d.[Distributor],
        d.[code] AS Current_code,
        s.[code] AS New_code,
        d.[DistributorScm] AS Current_DistributorScm,
        s.[DistributorScm] AS New_DistributorScm
    FROM [dbo].[Distributors] d
    INNER JOIN @Source s
        ON s.[Distributor] = d.[Distributor]
    ORDER BY d.[Distributor];

    -- Preview: data yang akan di-insert
    SELECT
        s.[Distributor],
        s.[code],
        s.[DistributorScm],
        @DefaultSubRegionId AS SubRegionId,
        @DefaultStatus AS [status]
    FROM @Source s
    WHERE NOT EXISTS (
        SELECT 1
        FROM [dbo].[Distributors] d
        WHERE d.[Distributor] = s.[Distributor]
    )
    ORDER BY s.[Distributor];

    -- UPDATE existing
    UPDATE d
    SET
        d.[code] = s.[code],
        d.[DistributorScm] = s.[DistributorScm]
    FROM [dbo].[Distributors] d
    INNER JOIN @Source s
        ON s.[Distributor] = d.[Distributor];

    SET @RowsUpdated = @@ROWCOUNT;

    -- INSERT new
    INSERT INTO [dbo].[Distributors] (
        [Distributor],
        [SubRegionId],
        [code],
        [DistributorScm],
        [status]
    )
    SELECT
        s.[Distributor],
        @DefaultSubRegionId,
        s.[code],
        s.[DistributorScm],
        @DefaultStatus
    FROM @Source s
    WHERE NOT EXISTS (
        SELECT 1
        FROM [dbo].[Distributors] d
        WHERE d.[Distributor] = s.[Distributor]
    );

    SET @RowsInserted = @@ROWCOUNT;

    COMMIT TRANSACTION;

    SELECT
        @RowsUpdated AS RowsUpdated,
        @RowsInserted AS RowsInserted,
        (SELECT COUNT(*) FROM @Source) AS TotalSourceRows,
        GETDATE() AS SyncedAt,
        'Upsert DistributorV1 berhasil' AS Message;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();

    SELECT
        0 AS RowsUpdated,
        0 AS RowsInserted,
        @ErrorMessage AS ErrorMessage;

    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
END CATCH;
GO
