SELECT [id]
      ,[distributor]
      ,[market_chanel]
      ,[customer_code]
      ,[customer_name]
      ,[kabupaten_kota]
      ,[fss_name]
      ,[fss_code]
      ,[fss_type]
      ,[sales_executive]
      ,[aspm]
      ,[status]
      ,[desc]
      ,[created_at]
      ,[updated_at]
      ,[customer_id]
      ,[master_fss_id]
  FROM [POWERAPPS].[dbo].[MP_FSS_KC]
