SELECT [distributor]
      ,[customer_code]
      ,[customer_name]
      ,[fss_code]
      ,[fss_name]
      ,[fss_type]
      ,[sales_executive]
      ,[fresh_dry]
      ,[rsm]
      ,[status]
      ,[desc]
      ,[created_at]
      ,[updated_at]
      ,[id]
  FROM [POWERAPPS].[dbo].[MP_FSS_DIRECT_NEW]
