SELECT [distributor]
      ,[region]
      ,[fresh_dry]
      ,[market_channel]
      ,[fss_name]
      ,[fss_code]
      ,[fss_type]
      ,[rsm]
      ,[status]
      ,[desc]
      ,[created_at]
      ,[updated_at]
      ,[id]
  FROM [POWERAPPS].[dbo].[MP_FSS_DIST_NEW]
