SELECT [distributor]
      ,[market_channel]
      ,[customer_code]
      ,[customer_name]
      ,[kabupaten_kota]
      ,[fss_name]
      ,[fss_code]
      ,[fss_type]
      ,[sales_executive]
      ,[rsm]
      ,[status]
      ,[desc]
      ,[created_at]
      ,[updated_at]
      ,[id]
  FROM [POWERAPPS].[dbo].[MP_FSS_OD_NEW]
