SELECT [code]
      ,[name]
      ,[city]
      ,[createdate]
      ,[distributor_id]
      ,[account_id]
      ,[account_trading_term]
      ,[regency_id]
      ,[created_at]
      ,[updated_at]
      ,[desc]
      ,[status]
      ,[btp]
      ,[btn]
      ,[top]
      ,[credit_limit]
      ,[GFcode]
      ,[npwp]
      ,[supply_chain]
      ,[nik]
      ,[va_gdi]
      ,[va_gi]
      ,[kecamatan]
      ,[id]
      ,[top50]
      ,[blok_release]
      ,[btg]
      ,[cutting]
      ,[accountCap]
      ,[shop_type]
      ,[shopper_type]
      ,[is_va]
  FROM [POWERAPPS].[dbo].[MP_CUSTOMER_NEW]

-- Set credit_limit menjadi NULL terlebih dahulu
UPDATE [POWERAPPS].[dbo].[MP_CUSTOMER_NEW]
SET [credit_limit] = 0;

-- Alter kolom credit_limit menjadi FLOAT
ALTER TABLE [POWERAPPS].[dbo].[MP_CUSTOMER_NEW]
ALTER COLUMN [credit_limit] FLOAT;