SELECT [code]
      ,[name]
      ,[city]
      ,[createdate]
      ,[distributor_id]
      ,[account_id]
      ,[account_trading_term]
      ,[regency_id]
      ,[created_at]
      ,[updated_at]
      ,[id]
      ,[status]
      ,[desc]
      ,[btp]
      ,[btn]
      ,[top]
      ,[credit_limit]
      ,[GFcode]
      ,[npwp]
      ,[supply_chain]
      ,[nik]
      ,[va_gdi]
      ,[va_gi]
      ,[kecamatan]
      ,[top50]
  FROM [POWERAPPS].[dbo].[MP_CUSTOMER] where distributor_id in (1, 32)
