-- Script untuk mengecek apakah kolom top50 sudah ada dan tipe datanya
USE [POWERAPPS]
GO

-- Cek apakah kolom top50 ada di tabel MP_CUSTOMER003
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'MP_CUSTOMER003' 
  AND COLUMN_NAME = 'top50'
GO

-- Cek apakah kolom top50 ada di tabel MP_CUSTOMER
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'MP_CUSTOMER' 
  AND COLUMN_NAME = 'top50'
GO

-- Tampilkan semua kolom di kedua tabel untuk referensi
PRINT '=== KOLOM DI MP_CUSTOMER003 ==='
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'MP_CUSTOMER003'
ORDER BY ORDINAL_POSITION
GO

PRINT '=== KOLOM DI MP_CUSTOMER ==='
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'MP_CUSTOMER'
ORDER BY ORDINAL_POSITION
GO
