SELECT [distributor_name]
      ,[customer_code]
      ,[customer_name]
      ,[account_name]
      ,[regency_name]
      ,[customer_createdate]
      ,[city]
      ,[account_trading_term]
      ,[shop_type]
      ,[shopper_type]
  FROM [POWERAPPS].[dbo].[MP_CUSTOMER_REFERENCE_05_06_2026]
